version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  gcsstorage:
    image: fsouza/fake-gcs-server:latest
    ports:
      - "4443:4443"
    volumes:
      - ${PWD}/data:/data/media_assets #default bucket
    command: ["-scheme", "http", "-port", "4443", "-external-url", "http://localhost:4443", "-backend", "memory"]
    networks:
      - app-network
  pubsub:
    image: google/cloud-sdk:latest
    entrypoint: gcloud
    command: ["beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085"]
    environment:
      GOOGLE_CLOUD_PROJECT: "test-project"
      PUBSUB_EMULATOR_HOST: "localhost:8085"
    ports:
      - "8085:8085"
    networks:
      - app-network
  cloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: ["-host", "0.0.0.0", "-port", "9090", "-queue", "projects/test-project/locations/us-central1/queues/image-queue"]
    ports:
      - "9090:9090"
    environment:
      GOOGLE_CLOUD_PROJECT: "test-project"
      CLOUD_TASKS_EMULATOR_HOST: "localhost:9090"
    networks:
      - app-network